version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: communication
      POSTGRES_PASSWORD: communication
    ports:
      - "7777:5432"
